@startuml
participant "AddBlockUseCase" as AddBlock
participant "BlockRepository" as BlockRepo
participant "Block" as Bloco

AddBlock -> BlockRepo: Obtém último bloco
BlockRepo --> AddBlock: Retorna último bloco
AddBlock -> Bloco: Define hash do bloco anterior
AddBlock -> Bloco: Calcula hash atual
AddBlock -> BlockRepo: Adiciona novo bloco
@enduml
