@startuml
participant "ValidateChainUseCase" as ValidateChain
participant "BlockRepository" as BlockRepo
participant "Block" as Bloco

ValidateChain -> BlockRepo: Obtém todos os blocos
BlockRepo --> ValidateChain: Retorna lista de blocos
loop para cada bloco na cadeia
    ValidateChain -> Bloco: Verifica hash atual
    ValidateChain -> Bloco: Verifica hash do bloco anterior
end
ValidateChain -> ValidateChain: Retorna resultado da validação
@enduml
