@startuml
participant "AddBlockUseCase" as AddBlock
participant "ProofOfWork" as PoW
participant "Block" as Bloco

AddBlock -> PoW: Inicia mineração
loop até condição ser satisfeita
    PoW -> Bloco: Incrementa nonce
    PoW -> Bloco: Recalcula hash
    PoW -> PoW: Verifica se hash atende à dificuldade
end
AddBlock <-- PoW: Retorna bloco minerado
@enduml
